language: java
cache:
  directories:
    - ~/.m2
install:
  - mvn test-compile -DskipTests=true -B -V
script:
  - mvn test jacoco:report -P coverage
after_success:
  - mvn coveralls:report -P coverage
